# Generated by Django 4.2.14 on 2024-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
