# Generated by Django 4.2.14 on 2024-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_userrestaurantslist"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="food_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
