# Generated by Django 4.2.14 on 2024-08-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0005_restaurant_food_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
