# Generated by Django 4.2.14 on 2024-07-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("nickname", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("reliability", models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
