repos:
  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate Commit Message
        entry: python validate_commit_msg.py
        language: python
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=188"]
        exclude: mustgou/settings.py
