# Generated by Django 4.2.14 on 2024-07-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_alter_friend_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="state",
            field=models.CharField(
                choices=[
                    ("request", "Request"),
                    ("approve", "Approve"),
                    ("deny", "Deny"),
                ],
                default="request",
                max_length=20,
            ),
        ),
    ]
