# Generated by Django 4.2.14 on 2024-08-01 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_alter_friend_friend_alter_friend_user"),
        ("friends", "0003_alter_friend_state"),
    ]

    operations = []
