# Generated by Django 4.2.14 on 2024-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0005_remove_friend_state_friendrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friend",
            name="state",
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                fields=("user", "friend"), name="unique_user_friend"
            ),
        ),
    ]
