# Generated by Django 4.2.14 on 2024-08-04 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0006_remove_friend_state_friend_unique_user_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
