# Generated by Django 4.2.14 on 2024-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0007_friend_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="isEvaluated",
            field=models.BooleanField(default=False),
        ),
    ]
