# Generated by Django 4.2.14 on 2024-08-14 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0008_friend_isevaluated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="isEvaluated",
            new_name="is_evaluated",
        ),
    ]
