# Generated by Django 4.2.14 on 2024-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_reliability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                default="default_profile_img.jpg", upload_to="profile_imgs"
            ),
        ),
    ]
