# Generated by Django 4.2.14 on 2024-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reliability",
            field=models.SmallIntegerField(default=80),
        ),
    ]
