# Generated by Django 4.2.14 on 2024-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_reliability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                default="default_profile_img.jpg", upload_to="profile_img/"
            ),
        ),
    ]
