# Generated by Django 4.2.14 on 2024-08-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0005_restaurant_food_type"),
        ("reviews", "0002_alter_recommend_user_alter_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="restaurants.restaurant",
            ),
        ),
    ]
