# Generated by Django 4.2.14 on 2024-08-07 02:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0005_remove_review_parent_reply"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommend",
            unique_together={("user", "review")},
        ),
    ]
