# Generated by Django 4.2.14 on 2024-08-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_alter_recommend_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommend",
            name="recommend",
            field=models.IntegerField(default=2),
        ),
    ]
